language: generic
sudo: false

jdk:
  - openjdk7
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"
script:
  - ./mvnw clean package -P full -Dsphinx.binUrl=https://github.com/hengyunabc/sphinx-binary/releases/download/v0.4.0.1/sphinx.linux-x86_64

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    - secure: "NBsHpn58viNVgS+0scV0N6jVIFyPNSmtymRiYecNGpzdEW1TlGw2DTmC/CVJlIjrc+HGvzARHnskQQNZPULvCNdITDvHtGq1JaTtycx7c3qi60mITUfjVFRGh/3ADjWMaSIGhptzsdt03WwPvcZs6QRkFeTTEjYAic6wLlvFgP5R9RAEEzpNzE7r2V/aoEfOvvDDA+eohNYrEm8dcPa0wYSGyk7KqB4tgENAeZsmi2bT/5pxAMq4OTQdbQvw31JeObFuWMmZ9vxR/sOhdm/4SNUnXEDH7CbpBWmlbp3Bfk+fB1Ir4PuyOZVx/KYfmOfknn7/HdA1XxVrEbvKIvCGAr8g7ZnIKu8LJirpSukmxVGl2mnB/GRBCEuuNSfwXY4V9l3iPxCAm32mzrdBvsQBdawEGyqunBZg66bJ9e8PIbzOAb0JNpjJcHqbJmZaUL2qrik7PDevj2DFTR1u5Iv/Bpnn+sAy+LX/YDpZoPELoySKgPReFY4zuXP6y3kovairM1QEXbMfxrJwZNCjIsWQ9KaNNYGDREAy0Vmh7tFyoj6IiLd4unN1IYcYeUe5lfOizphGhBNX38cT+qISK1I/bDFHGjaqKMu+YwMLKRnyh3ch0/OWe/2XHVirhHHDLu3JcP4VC7v9waUfwu35pKHUHgl1jFGYGTI4lC9w8s3V5YA="
  file_glob: true
  file: "packaging/target/*.zip"
  skip_cleanup: true
  on:
    tags: true

